<?php
/**
 * Title Format Library
 * 100+ unique title formats for SEO diversity
 * Variables: {service}, {area}, {company}
 */

return [
    // Professional/Quality (20 formats)
    "Professional {service} in {area}, Chennai | {company}",
    "Expert {service} Installation in {area}, Chennai | {company}",
    "Quality {service} Services in {area}, Chennai | {company}",
    "Premium {service} Solutions for {area}, Chennai | {company}",
    "Certified {service} Specialists in {area}, Chennai | {company}",
    "Licensed {service} Contractors in {area}, Chennai | {company}",
    "Experienced {service} Installers in {area}, Chennai | {company}",
    "Skilled {service} Technicians in {area}, Chennai | {company}",
    "Advanced {service} Systems in {area}, Chennai | {company}",
    "Modern {service} Installation in {area}, Chennai | {company}",
    "High-Quality {service} in {area}, Chennai | {company}",
    "Superior {service} Solutions for {area}, Chennai | {company}",
    "Top-Grade {service} Services in {area}, Chennai | {company}",
    "First-Class {service} in {area}, Chennai | {company}",
    "Premium-Quality {service} for {area}, Chennai | {company}",
    "Professional-Grade {service} in {area}, Chennai | {company}",
    "Commercial-Grade {service} for {area}, Chennai | {company}",
    "Residential {service} Experts in {area}, Chennai | {company}",
    "Elite {service} Services in {area}, Chennai | {company}",
    "Master {service} Installation in {area}, Chennai | {company}",
    
    // Best/Top Rankings (20 formats)
    "Best {service} Service in {area}, Chennai | {company}",
    "Top {service} Providers in {area}, Chennai | {company}",
    "#1 {service} Installation in {area}, Chennai | {company}",
    "Leading {service} Company in {area}, Chennai | {company}",
    "Premier {service} Services in {area}, Chennai | {company}",
    "Top-Rated {service} in {area}, Chennai | {company}",
    "Best-in-Class {service} in {area}, Chennai | Free Quote",
    "Award-Winning {service} in {area}, Chennai | {company}",
    "Most Trusted {service} in {area}, Chennai | {company}",
    "Most Reliable {service} for {area}, Chennai | {company}",
    "Highly-Rated {service} Installation in {area}, Chennai",
    "5-Star {service} Services in {area}, Chennai | {company}",
    "Top-Tier {service} Solutions for {area}, Chennai",
    "First-Choice {service} in {area}, Chennai | Call Now",
    "Excellence in {service} for {area}, Chennai | {company}",
    "Outstanding {service} Services in {area}, Chennai",
    "Exceptional {service} Solutions in {area}, Chennai",
    "Unmatched {service} Quality in {area}, Chennai | {company}",
    "Ultimate {service} Solutions in {area}, Chennai | {company}",
    "Finest {service} Installation in {area}, Chennai | {company}",
    
    // Trust/Reliability (15 formats)
    "Trusted {service} Installers in {area}, Chennai | {company}",
    "Reliable {service} Services for {area}, Chennai | 5-Year Warranty",
    "Dependable {service} Solutions in {area}, Chennai | {company}",
    "Trustworthy {service} Providers in {area}, Chennai",
    "Safe {service} Installation in {area}, Chennai | Certified",
    "Guaranteed {service} Installation in {area}, Chennai | {company}",
    "Warrantied {service} Solutions in {area}, Chennai | 5 Years",
    "Insured {service} Services for {area}, Chennai | {company}",
    "Assured {service} Quality in {area}, Chennai | {company}",
    "Established {service} Company in {area}, Chennai Since 2010",
    "Time-Tested {service} Services in {area}, Chennai | {company}",
    "Proven {service} Solutions for {area}, Chennai | {company}",
    "Veteran {service} Installers in {area}, Chennai | 15+ Years",
    "Long-Standing {service} Services in {area}, Chennai",
    "Legacy {service} Providers in {area}, Chennai | {company}",
    
    // Features/Benefits (15 formats)
    "Affordable {service} Installation in {area}, Chennai | {company}",
    "Budget-Friendly {service} Services in {area}, Chennai | Best Prices",
    "Cost-Effective {service} Solutions for {area}, Chennai",
    "Economical {service} in {area}, Chennai | Competitive Rates",
    "Value-for-Money {service} in {area}, Chennai | {company}",
    "Fast {service} Installation in {area}, Chennai | Same Day",
    "Quick {service} Services for {area}, Chennai | {company}",
    "Same-Day {service} Services in {area}, Chennai | Call Now",
    "Prompt {service} Installation in {area}, Chennai | {company}",
    "24/7 {service} Services in {area}, Chennai | Emergency Support",
    "Durable {service} Installation in {area}, Chennai | 7+ Years Life",
    "Long-Lasting {service} Solutions for {area}, Chennai | {company}",
    "Heavy-Duty {service} Services in {area}, Chennai | Industrial Grade",
    "Weather-Resistant {service} in {area}, Chennai | UV Protected",
    "Waterproof {service} Services in {area}, Chennai | Monsoon Ready",
    
    // Innovation/Technology (15 formats)
    "Advanced {service} Technology in {area}, Chennai | {company}",
    "Innovative {service} Solutions for {area}, Chennai | Modern",
    "State-of-the-Art {service} in {area}, Chennai | {company}",
    "Cutting-Edge {service} Solutions for {area}, Chennai",
    "Next-Generation {service} in {area}, Chennai | Latest Tech",
    "High-Tech {service} Services in {area}, Chennai | {company}",
    "Smart {service} Solutions for {area}, Chennai | IoT Ready",
    "Eco-Friendly {service} Solutions in {area}, Chennai | Green",
    "Sustainable {service} Services in {area}, Chennai | Environment Safe",
    "Green {service} Installation for {area}, Chennai | {company}",
    "Non-Toxic {service} Solutions for {area}, Chennai | Safe",
    "Energy-Efficient {service} in {area}, Chennai | {company}",
    "Low-Impact {service} Installation in {area}, Chennai",
    "Carbon-Neutral {service} Solutions for {area}, Chennai",
    "Planet-Friendly {service} Services in {area}, Chennai",
    
    // Custom/Specialized (15 formats)
    "Custom {service} Installation in {area}, Chennai | Tailored",
    "Customized {service} Solutions for {area}, Chennai | {company}",
    "Bespoke {service} Installation in {area}, Chennai | Made-to-Order",
    "Personalized {service} Solutions for {area}, Chennai | {company}",
    "Specialized {service} Solutions in {area}, Chennai | Expert",
    "Complete {service} Solutions in {area}, Chennai | Full Service",
    "Comprehensive {service} Services for {area}, Chennai | All-Inclusive",
    "End-to-End {service} Solutions for {area}, Chennai | {company}",
    "Turnkey {service} Installation in {area}, Chennai | Complete Package",
    "One-Stop {service} Solutions in {area}, Chennai | Everything Included",
    "Integrated {service} Services for {area}, Chennai | {company}",
    "Flexible {service} Solutions in {area}, Chennai | Adaptable",
    "Versatile {service} Services for {area}, Chennai | Multi-Purpose",
    "All-Weather {service} Solutions for {area}, Chennai | Year-Round",
    "On-Demand {service} Services in {area}, Chennai | Anytime"
];
